### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by yackinoff69** [Flipnote-Collective/flipnote-fetcher#3]
not a issue but could you do like a youtube tutorial on how to do this? it would help a lot

**Comment by jaames** [comment]
Not really; for what it's worth, this isn't really meant to be a 'user friendly' tool -- it's more a proof-of-concept than anything else. I was hoping that someone else would create a nice user interface around it but so far I guess nobody has had the motivation to do so. 

It's a command line tool, so if you want to use it, you'll need to learn how to use the **command line**. The command line is a little techy and can work a bit differently depending on what operating system you're on, so it wouldn't really be productive for me to make a simple beginner-level tutorial since there's lots of variables and system-dependant stuff that would need covering before I could even get to running the script.

If you really want to use this (and don't want to wait for someone to make a GUI), I'd recommend looking into how to use the command line on your system, and using command line to run Python scripts. Then come back and check the usage section on this project's front page: https://github.com/Flipnote-Collective/flipnote-fetcher#usage
